### ISSUE TITLE
Add support for Stripe ^7.0

### ISSUE THREAD

**Issue by mattcookdev** [JacobBennett/StripeTestToken#13]
We are no longer able to use this due to a composer installation constraint. Hopefully you can update it to accept ^7.0 of `stripe-php`.

![image](https://user-images.githubusercontent.com/22277786/68539564-cb70e880-03c0-11ea-90b1-b7bf53cea87a.png)

**Comment by JacobBennett** [comment]
Fixed in newest release of `v2.0.1`
