### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by relu-xz** [JacobBennett/StripeTestToken#7]
Hi.

In the examples, the param **`curreny`** must be **`currency`**.

**Comment by JacobBennett** [comment]
Would you like to submit a PR with the change? Would be happy to approve it 👍

**Comment by relu-xz** [comment]
Done =)

**Comment by JacobBennett** [comment]
close in #8

**Comment by JacobBennett** [comment]
Thank you @zorobabel
